blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/REPLACE_ME/security
    about: Please report security vulnerabilities privately per SECURITY.md
